import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Fix for __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import product and location data
import { productDetailsData } from '../src/data/productDetailsData.js';
import { globalLocations } from '../src/data/locations.js';
import { indiaLocations } from '../src/data/indiaLocations.js';
import { indiaPortsLocations } from '../src/data/indiaPortsLocations.js';

const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');
const materialsDir = path.join(distDir, 'materials');
const exportDir = path.join(distDir, 'export');
const indiaDir = path.join(distDir, 'india');
const importIndiaDir = path.join(distDir, 'import-india');

// Ensure directories exist in dist
if (!fs.existsSync(materialsDir)) fs.mkdirSync(materialsDir, { recursive: true });
if (!fs.existsSync(exportDir)) fs.mkdirSync(exportDir, { recursive: true });
if (!fs.existsSync(indiaDir)) fs.mkdirSync(indiaDir, { recursive: true });
if (!fs.existsSync(importIndiaDir)) fs.mkdirSync(importIndiaDir, { recursive: true });

// Read the base index.html generated by Vite
const indexPath = path.join(distDir, 'index.html');
const baseHtml = fs.readFileSync(indexPath, 'utf-8');

// Helper to inject meta tags into head
const injectMeta = (html, title, description, image, url, schemaJson) => {
  const fullUrl = `https://anchorstoneglobal.co.in${url}`;
  
  const metaTags = `
    <title>${title}</title>
    <meta name="description" content="${description}" />
    <link rel="canonical" href="${fullUrl}" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />
    <meta property="og:image" content="https://anchorstoneglobal.co.in${image}" />
    <meta property="og:url" content="${fullUrl}" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary_large_image" />
    ${schemaJson ? `<script type="application/ld+json">\n${JSON.stringify(schemaJson)}\n    </script>` : ''}
  `;
  
  // Replace the default <title> tag with our rich meta tags
  return html.replace(/<title>.*?<\/title>/i, metaTags);
};

// 1. Update the main index.html (Home Page)
const homeTitle = "Global Scrap Material Supplier & Plastic Recycling | Anchorstone Global";
const homeDesc = "Anchorstone Global LLP specializes in the supply and export of bulk plastic scraps, metal scraps, and reprocessed granules globally from Ahmedabad.";
const homeSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Anchorstone Global LLP",
  "url": "https://anchorstoneglobal.co.in",
  "logo": "https://anchorstoneglobal.co.in/logo.png",
  "description": homeDesc,
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "SHED NO. 19, HITENDRANAGAR DIAMAND PARK FEEDER NO.9",
    "addressLocality": "Ahmedabad",
    "addressRegion": "Gujarat",
    "postalCode": "382340",
    "addressCountry": "IN"
  }
};
const homeHtml = injectMeta(baseHtml, homeTitle, homeDesc, "/logo.png", "/", homeSchema);
fs.writeFileSync(indexPath, homeHtml);

const cachePath = path.join(rootDir, 'src', 'data', 'keywordCache.json');
let keywordCache = {};
if (fs.existsSync(cachePath)) {
  keywordCache = JSON.parse(fs.readFileSync(cachePath, 'utf-8'));
}

const getVolume = (slug) => {
  return keywordCache[slug] ? keywordCache[slug].volume : -1;
};

const getBestKeyword = (slug, defaultName) => {
  return keywordCache[slug] && keywordCache[slug].best_keyword ? keywordCache[slug].best_keyword : defaultName;
};

// 2. Generate a physical .html file for every product
let generatedCount = 0;
for (const slug in productDetailsData) {
  if (getVolume(slug) === 0) continue;
  const product = productDetailsData[slug];
  
  const bestKeyword = getBestKeyword(slug, product.name);
  const title = product.seoTitle || `${bestKeyword} | Anchorstone Global Materials`;
  const description = product.seoDescription || product.sourceText;
  const image = product.heroImage;
  const url = `/materials/${slug}.html`;
  
  const schemaJson = {
    "@context": "https://schema.org",
    "@type": "Product",
    "name": bestKeyword,
    "image": `https://anchorstoneglobal.co.in${image}`,
    "description": description,
    "brand": {
      "@type": "Brand",
      "name": "Anchorstone Global"
    },
    "offers": {
      "@type": "Offer",
      "url": `https://anchorstoneglobal.co.in${url}`,
      "priceCurrency": "USD",
      "price": "0",
      "availability": "https://schema.org/InStock",
      "seller": {
        "@type": "Organization",
        "name": "Anchorstone Global LLP"
      }
    }
  };
  const productHtml = injectMeta(baseHtml, title, description, image, url, schemaJson);
  
  const productFilePath = path.join(materialsDir, `${slug}.html`);
  fs.writeFileSync(productFilePath, productHtml);
  generatedCount++;
}

// 3. Generate Geo-Matrix HTML files
let geoCount = 0;
for (const slug in productDetailsData) {
  if (getVolume(slug) === 0) continue;
  const product = productDetailsData[slug];
  for (const location in globalLocations) {
    const locationName = globalLocations[location];
    const bestKeyword = getBestKeyword(slug, product.name);
    const title = `Import ${bestKeyword} to ${locationName} | Bulk Suppliers`;
    const description = `Anchorstone Global specializes in exporting bulk ${bestKeyword} to ${locationName}. Contact us today for a quote!`;
    const image = product.heroImage;
    const url = `/export/${location}/${slug}.html`;

    const schemaJson = {
      "@context": "https://schema.org",
      "@type": "Product",
      "name": `${bestKeyword} Export to ${locationName}`,
      "image": `https://anchorstoneglobal.co.in${image}`,
      "description": description,
      "brand": {
        "@type": "Brand",
        "name": "Anchorstone Global"
      },
      "offers": {
        "@type": "Offer",
        "url": `https://anchorstoneglobal.co.in${url}`,
        "priceCurrency": "USD",
        "price": "0",
        "availability": "https://schema.org/InStock",
        "areaServed": locationName,
        "seller": {
          "@type": "Organization",
          "name": "Anchorstone Global LLP"
        }
      }
    };
    const productHtml = injectMeta(baseHtml, title, description, image, url, schemaJson);

    const locationDir = path.join(exportDir, location);
    if (!fs.existsSync(locationDir)) {
      fs.mkdirSync(locationDir, { recursive: true });
    }

    const geoFilePath = path.join(locationDir, `${slug}.html`);
    fs.writeFileSync(geoFilePath, productHtml);
    geoCount++;
  }
}

// 4. Generate India Geo-Matrix HTML files
let indiaCount = 0;
for (const slug in productDetailsData) {
  if (getVolume(slug) === 0) continue;
  const product = productDetailsData[slug];
  for (const location in indiaLocations) {
    const locationName = indiaLocations[location];
    const bestKeyword = getBestKeyword(slug, product.name);
    const title = `Buy ${bestKeyword} in ${locationName}`;
    const description = `Anchorstone Global and The Polylot Company are leading suppliers and distributors of bulk ${bestKeyword} across ${locationName}. Contact us for domestic pricing!`;
    const image = product.heroImage;
    const url = `/india/${location}/${slug}.html`;

    const schemaJson = {
      "@context": "https://schema.org",
      "@type": "Product",
      "name": `${bestKeyword} in ${locationName}`,
      "image": `https://anchorstoneglobal.co.in${image}`,
      "description": description,
      "brand": {
        "@type": "Brand",
        "name": "Anchorstone Global"
      },
      "offers": {
        "@type": "Offer",
        "url": `https://anchorstoneglobal.co.in${url}`,
        "priceCurrency": "INR",
        "price": "0",
        "availability": "https://schema.org/InStock",
        "areaServed": locationName,
        "seller": {
          "@type": "Organization",
          "name": "Anchorstone Global LLP"
        }
      }
    };
    const productHtml = injectMeta(baseHtml, title, description, image, url, schemaJson);

    const locationDir = path.join(indiaDir, location);
    if (!fs.existsSync(locationDir)) {
      fs.mkdirSync(locationDir, { recursive: true });
    }

    const geoFilePath = path.join(locationDir, `${slug}.html`);
    fs.writeFileSync(geoFilePath, productHtml);
    indiaCount++;
  }
}

// 5. Generate India Ports (Import) Geo-Matrix HTML files
let indiaPortsCount = 0;
for (const slug in productDetailsData) {
  if (getVolume(slug) === 0) continue;
  const product = productDetailsData[slug];
  for (const location in indiaPortsLocations) {
    const locationName = indiaPortsLocations[location];
    const bestKeyword = getBestKeyword(slug, product.name);
    const title = `Import ${bestKeyword} to ${locationName} | Bulk Suppliers`;
    const description = `Anchorstone Global specializes in supplying bulk ${bestKeyword} directly to ${locationName}. Contact us today for import and logistics quotes!`;
    const image = product.heroImage;
    const url = `/import-india/${location}/${slug}.html`;

    const schemaJson = {
      "@context": "https://schema.org",
      "@type": "Product",
      "name": `Import ${bestKeyword} to ${locationName}`,
      "image": `https://anchorstoneglobal.co.in${image}`,
      "description": description,
      "brand": {
        "@type": "Brand",
        "name": "Anchorstone Global"
      },
      "offers": {
        "@type": "Offer",
        "url": `https://anchorstoneglobal.co.in${url}`,
        "priceCurrency": "INR",
        "price": "0",
        "availability": "https://schema.org/InStock",
        "areaServed": locationName,
        "seller": {
          "@type": "Organization",
          "name": "Anchorstone Global LLP"
        }
      }
    };
    const productHtml = injectMeta(baseHtml, title, description, image, url, schemaJson);

    const locationDir = path.join(importIndiaDir, location);
    if (!fs.existsSync(locationDir)) {
      fs.mkdirSync(locationDir, { recursive: true });
    }

    const geoFilePath = path.join(locationDir, `${slug}.html`);
    fs.writeFileSync(geoFilePath, productHtml);
    indiaPortsCount++;
  }
}

console.log(`✅ Successfully injected Open Graph tags!`);
console.log(`- Updated main index.html`);
console.log(`- Generated ${generatedCount} static product HTML files.`);
console.log(`- Generated ${geoCount} Global Geo-Matrix static HTML files.`);
if (indiaCount > 40000) {
  console.log(`- Generated 40000 India-1 Geo-Matrix static HTML files.`);
  console.log(`- Generated ${indiaCount - 40000} India-2 Geo-Matrix static HTML files.`);
} else {
  console.log(`- Generated ${indiaCount} India Geo-Matrix static HTML files.`);
}
console.log(`- Generated ${indiaPortsCount} India Ports Geo-Matrix static HTML files.`);
